// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbjemqyjgnxqonaabddl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiamVtcXlqZ254cW9uYWFiZGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODA2NTEsImV4cCI6MjA2ODY1NjY1MX0.TPDkFzNHucwmFGzry-1GCtu2iOW3YaYApDH4GmahlwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});